#!/usr/bin/bash
#globel shell configuration for bash and zsh

alias wtr='curl wttr.in/zurich'
alias yt='ytfzf -t'
alias tch_on='xinput set-prop 14 "Device Enabled" 1'
alias tch_off='xinput set-prop 14 "Device Enabled" 0'
alias la='ls -hals'
alias lg='ls | grep -i'
alias transde='trans -t de -s en' 
alias transen='trans -t en -s de' 
alias transes='trans -t es -s en' 
alias transes_en='trans -t en -s es' 
alias nv='nvim'
alias vkill='rm ~/.local/share/nvim/swap/*'
alias vs='nvim -S session.vim'
alias rn='ranger'
alias bt='btop'
alias python='python3'
alias ftp='stftp -p 2121 -u nls '
alias pa='/usr/bin/ncpamixer'
alias ls_path="echo $PATH | sed  's|:|\n|g' | xargs ls"
alias battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "State|to\ |time|percentage"'
alias cn="cnfile"

export EDITOR='nvim'
export VISUAL='nvim'
export DWM='/usr/arcolinux-dwm/etc/skel/.config/arco-dwm'
export git_token="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"
export nvrc='$HOME/.config/nvim/init.vim'
export LIB='/usr/include'
export TERM=rxvt-unicode
export URXVT='urxvt'
export BROWSER='firefox'
export PATH=$PATH:/home/nls/tools/node-v14.15.4-linux-x64/bin:/home/nls/.local/bin:/home/nls/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/nls/cpp/:/home/nls/py/pytools:/home/nls/py/cnav:/home/nls/.fzf/bin:/home/nls/sys_cfg
